"""admin table

Revision ID: 19504096d044
Revises: 4db8e6252050
Create Date: 2024-07-11 16:51:03.639075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19504096d044'
down_revision = '4db8e6252050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_email'))

    op.drop_table('admins')
    # ### end Alembic commands ###
