"""Delete Photo model, and add field link_photo_by_procedure in Price model

Revision ID: c946a88e42ba
Revises: e5a881740c0a
Create Date: 2024-07-22 16:19:19.689261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c946a88e42ba'
down_revision = 'e5a881740c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo_procedure', schema=None) as batch_op:
        batch_op.drop_index('ix_photo_procedure_procedure_id')

    op.drop_table('photo_procedure')
    with op.batch_alter_table('price_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_photo_by_procedure', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list', schema=None) as batch_op:
        batch_op.drop_column('link_photo_by_procedure')

    op.create_table('photo_procedure',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('procedure_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('link_photo_by_procedure', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['price_list.id'], name='photo_procedure_procedure_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='photo_procedure_pkey')
    )
    with op.batch_alter_table('photo_procedure', schema=None) as batch_op:
        batch_op.create_index('ix_photo_procedure_procedure_id', ['procedure_id'], unique=False)

    # ### end Alembic commands ###
